# Generated by Django 5.2.1 on 2025-05-27 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'Tổng quát'), ('symptoms', 'Triệu chứng'), ('treatments', 'Điều trị'), ('prevention', 'Phòng ngừa'), ('emergency', 'Cấp cứu'), ('medications', 'Thuốc'), ('lifestyle', 'Lối sống')], max_length=20)),
                ('question', models.TextField(help_text='Câu hỏi hoặc từ khóa')),
                ('answer', models.TextField(help_text='Câu trả lời')),
                ('keywords', models.TextField(help_text='Từ khóa liên quan (phân cách bằng dấu phẩy)')),
                ('confidence_score', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kiến thức chatbot',
                'verbose_name_plural': 'Kiến thức chatbot',
            },
        ),
        migrations.CreateModel(
            name='HealthSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('severity_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('related_conditions', models.TextField(blank=True, null=True)),
                ('advice', models.TextField(help_text='Lời khuyên cho triệu chứng này')),
            ],
            options={
                'verbose_name': 'Triệu chứng sức khỏe',
                'verbose_name_plural': 'Triệu chứng sức khỏe',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(default='Cuộc trò chuyện mới', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phiên chat',
                'verbose_name_plural': 'Phiên chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'Người dùng'), ('bot', 'Chatbot'), ('system', 'Hệ thống')], max_length=10)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, help_text='Dữ liệu bổ sung', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Tin nhắn chat',
                'verbose_name_plural': 'Tin nhắn chat',
                'ordering': ['created_at'],
            },
        ),
    ]
